
---
title: "Power"
output: html_document
---

---

The probability of a type II error is $\beta$. In other words, it is the probability of *not* rejecting $H_o$ when it is false.

Therefore, probability of rejecting $H_o$ when it is false will be $1 - \beta$. And this is exactly the definition of *POWER*:

<br>

$POWER \, = \, 1\,-\,\beta$

<br>

Power is exactly the probability that the test statistic lies in the rejection region *under* the premise that $H_a$ is correct.

For a single-group mean test we are comparing a normalized mean to a $t$ quantile to test if the group mean belongs to a different population, i.e. $H_a: \mu_a>\mu_o$.

<br>

$p\,\Big(\Large\frac{\bar X - \mu_o}{s/\sqrt{n}}\,> t_{1-\alpha,\,n-1}|\mu=\mu_a\Big)$

<br>

However, if $n$ is large we can do instead normal calculations:

<br>

$p\,\Big(\Large\frac{\bar X - \mu_o}{s/\sqrt{n}}\,> z_{1-\alpha}|\mu=\mu_a\Big)$

<br>

$\Large=\Big(\Large\frac{\bar X - \mu_a \, + \mu_a -\mu_o}{s/\sqrt{n}}\,> z_{1-\alpha}|\mu=\mu_a\Big)$

<br>

$\Large=\Big(\Large\frac{\bar X - \mu_a}{\sigma/\sqrt{n}} > \,z_{1-\alpha}\, -\frac{\mu_a -\mu_o}{s/\sqrt{n}}|\mu=\mu_a\Big)$

<br>

$\Large=\Big(Z> \, z_{1-\alpha} -\frac{\mu_a -\mu_o}{s/\sqrt{n}}|\mu=\mu_a\Big)$


---

<a href="http://rinterested.github.io/STATISTICS/Index.html">Home Page</a>